openapi: 3.0.1
info:
  title: document
  version: "1.0"
servers:
- url: http://localhost:12000
security:
- jwt: []
paths:
  /npl/document/-/openapi.json:
    get:
      operationId: _getOpenAPI
      responses:
        "200":
          description: The OpenAPI spec
          content:
            application/json:
              schema:
                type: object
      security: []
  /npl/document/Document/:
    get:
      operationId: _getDocumentList
      parameters:
      - name: page
        in: query
        required: false
        schema:
          minimum: 1
          type: integer
      - name: pageSize
        in: query
        required: false
        schema:
          maximum: 100
          minimum: 1
          type: integer
          default: 25
      - name: includeCount
        in: query
        description: "Include `totalItems` and `totalPages` in the response if set.\
          \ This option is very expensive, so should be avoided when possible."
        required: false
        schema:
          type: boolean
          default: false
      - name: sort
        in: query
        description: "Sort the protocol list by the given type. Possible values are\
          \ [created, modified]. Requires `order` parameter to be set."
        required: false
        schema:
          type: string
      - name: order
        in: query
        description: Return search results in the given order. Possible values are
          'asc' and 'desc'. Requires `sort` parameter to be set.
        required: false
        schema:
          type: string
      - name: state
        in: query
        description: "Filter protocols whose current state is one of the provided\
          \ values. May be repeated: e.g. ?state=active&state=paused"
        required: false
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: modifiedAfter
        in: query
        description: Filter protocols modified after the given timestamp (inclusive).
          The timestamp must be in ISO-8601 format.
        required: false
        schema:
          type: string
          format: date-time
      - name: modifiedBefore
        in: query
        description: Filter protocols modified before the given timestamp (inclusive).
          The timestamp must be in ISO-8601 format.
        required: false
        schema:
          type: string
          format: date-time
      - name: createdAfter
        in: query
        description: Filter protocols created after the given timestamp (inclusive).
          The timestamp must be in ISO-8601 format.
        required: false
        schema:
          type: string
          format: date-time
      - name: createdBefore
        in: query
        description: Filter protocols created before the given timestamp (inclusive).
          The timestamp must be in ISO-8601 format.
        required: false
        schema:
          type: string
          format: date-time
      - $ref: "#/components/parameters/API_Version"
      - $ref: "#/components/parameters/NPL_Tag"
      responses:
        "200":
          description: All accessible protocol instances of this type
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Document_List"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "500":
          $ref: "#/components/responses/500"
    post:
      operationId: _createDocument
      parameters:
      - $ref: "#/components/parameters/API_Version"
      - $ref: "#/components/parameters/NPL_Tag"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Document_Create"
        required: true
      responses:
        "200":
          description: The new protocol instance
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Document"
        "204":
          description: No Content
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "500":
          $ref: "#/components/responses/500"
  /npl/document/Document/{id}/:
    get:
      operationId: _getDocumentByID
      parameters:
      - $ref: "#/components/parameters/ProtocolID"
      - $ref: "#/components/parameters/API_Version"
      - $ref: "#/components/parameters/NPL_Tag"
      responses:
        "200":
          description: The protocol instance with this ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Document"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /npl/document/Document/{id}/edit:
    post:
      operationId: Document_edit
      parameters:
      - $ref: "#/components/parameters/ProtocolID"
      - $ref: "#/components/parameters/API_Version"
      - $ref: "#/components/parameters/NPL_Tag"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Document_Edit_Command"
        required: true
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                description: Unit
                nullable: false
        "204":
          description: No Content
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /npl/document/Document/{id}/requestReview:
    post:
      operationId: Document_requestReview
      parameters:
      - $ref: "#/components/parameters/ProtocolID"
      - $ref: "#/components/parameters/API_Version"
      - $ref: "#/components/parameters/NPL_Tag"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                description: Unit
                nullable: false
        "204":
          description: No Content
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /npl/document/Document/{id}/approve:
    post:
      operationId: Document_approve
      parameters:
      - $ref: "#/components/parameters/ProtocolID"
      - $ref: "#/components/parameters/API_Version"
      - $ref: "#/components/parameters/NPL_Tag"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                description: Unit
                nullable: false
        "204":
          description: No Content
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
components:
  schemas:
    _Party:
      required:
      - claims
      type: object
      properties:
        claims:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
      example:
        claims:
          preferred_email:
          - john.doe@example.com
    _Period:
      required:
      - days
      - months
      - weeks
      - years
      type: object
      properties:
        days:
          type: integer
        weeks:
          type: integer
        months:
          type: integer
        years:
          type: integer
    _Error:
      type: object
      properties:
        errorType:
          type: string
        id:
          type: string
          format: uuid
        idType:
          type: string
        message:
          type: string
        error:
          type: string
          nullable: true
        origin:
          type: object
          properties:
            value:
              type: string
            code:
              type: integer
              format: int32
            originType:
              type: string
            id:
              type: string
            message:
              type: string
          nullable: true
        stackTrace:
          type: string
          nullable: true
        clientStackTrace:
          type: array
          nullable: true
          items:
            type: object
            properties:
              name:
                type: string
              protocolId:
                type: string
                format: uuid
                nullable: true
              elementType:
                type: string
              location:
                type: object
                properties:
                  file:
                    type: string
                  line:
                    type: integer
                    format: int32
                  sourceRef:
                    type: object
                    properties:
                      path:
                        type: string
                      commit:
                        type: string
                    nullable: true
            nullable: true
    Document:
      required:
      - '@actions'
      - '@id'
      - '@parties'
      - '@state'
      - content
      type: object
      properties:
        '@id':
          type: string
          format: uuid
        '@parties':
          $ref: "#/components/schemas/Document_Parties"
        '@actions':
          $ref: "#/components/schemas/Document_Actions"
        '@state':
          $ref: "#/components/schemas/Document_States"
        content:
          type: string
      readOnly: true
    Document_Parties:
      required:
      - approver
      - editor
      type: object
      properties:
        editor:
          $ref: "#/components/schemas/_Party"
        approver:
          $ref: "#/components/schemas/_Party"
    Document_Actions:
      type: object
      properties:
        edit:
          type: string
          format: uri
          example: http://localhost:12000/npl/document/Document/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/edit
        requestReview:
          type: string
          format: uri
          example: http://localhost:12000/npl/document/Document/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/requestReview
        approve:
          type: string
          format: uri
          example: http://localhost:12000/npl/document/Document/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/approve
    Document_List:
      required:
      - items
      type: object
      properties:
        '@prev':
          type: string
          format: uri
          example: http://localhost:12000/npl/document/Document/?page=1&pageSize=10
        '@next':
          type: string
          format: uri
          example: http://localhost:12000/npl/document/Document/?page=3&pageSize=10
        items:
          type: array
          items:
            $ref: "#/components/schemas/Document"
        page:
          type: integer
        totalItems:
          type: integer
          description: Total number of accessible protocol instances. Only included
            if the `includeCount` query parameter was set.
          nullable: true
        totalPages:
          type: integer
          description: Total number of accessible pages. Only included if the `includeCount`
            query parameter was set.
          nullable: true
    Document_Create:
      required:
      - '@parties'
      - content
      type: object
      properties:
        content:
          type: string
        '@parties':
          $ref: "#/components/schemas/Document_Parties"
    Document_States:
      type: string
      enum:
      - created
      - inReview
      - approved
    Document_Edit_Command:
      required:
      - newContent
      type: object
      properties:
        newContent:
          type: string
  responses:
    "400":
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/_Error"
    "401":
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/_Error"
    "403":
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/_Error"
    "404":
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/_Error"
    "500":
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/_Error"
  parameters:
    API_Version:
      name: X-NPL-API
      in: header
      description: Optional parameter to require a specific API version
      required: false
      schema:
        type: string
    NPL_Tag:
      name: X-NPL-TAG
      in: header
      description: Optional parameter to require a specific NPL Tag
      required: false
      schema:
        type: string
    ProtocolID:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
