volumes:
  keycloak-db: { }
  keycloak-provisioning: { }

services:
  engine:
    image: ghcr.io/noumenadigital/npl-integrations/engine:latest
    build:
      context: npl
    ports:
      - "12000:12000"
      - "12400:12400"
      - "12700:12700"
    environment:
      ENGINE_DEV_MODE: false
      ENGINE_ALLOWED_ISSUERS: http://keycloak:11000/realms/${VITE_NC_APP_SLUG:-nplintegrations},http://localhost:11000/realms/${VITE_NC_APP_SLUG:-nplintegrations}
      ENGINE_DB_URL: "jdbc:postgresql://engine-db:5432/engine"
      ENGINE_DB_USER: npl-integrations
      ENGINE_DB_PASSWORD: secret
      ENGINE_DB_HISTORY_USER: history
      ENGINE_DB_HISTORY_SCHEMA: history
      ENGINE_DB_READ_MODEL_USER: postgraphile
      ENGINE_ISSUER_OVERRIDE: http://keycloak:11000/realms/${VITE_NC_APP_SLUG:-nplintegrations}
      SWAGGER_ENGINE_URL: http://localhost:12000
      SWAGGER_SECURITY_AUTH_URL: http://localhost:11000/realms/${VITE_NC_APP_SLUG:-nplintegrations}
      SWAGGER_SECURITY_CLIENT_ID: ${VITE_NC_APP_SLUG:-nplintegrations}
      SWAGGER_SECURITY_CLIENT_SECRET:
      ENGINE_MANAGEMENT_HOST: 0.0.0.0
      ENGINE_MANAGEMENT_PORT: 12400
    depends_on:
      engine-db:
        condition: service_started
      keycloak:
        condition: service_healthy
  nginx-proxy:
    image: nginx:latest
    ports:
      - "12001:12001"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/snippets:/etc/nginx/snippets
    depends_on:
      engine:
        condition: service_healthy

  engine-db:
    image: postgres:14.4-alpine
    mem_limit: 256m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: engine
      ENGINE_DB_USER: npl-integrations
      ENGINE_DB_PASSWORD: secret
      HISTORY_DB_USER: history
      HISTORY_DB_PASSWORD: secret
      HISTORY_DB_SCHEMA: history
      READ_MODEL_DB_USER: postgraphile
      READ_MODEL_DB_PASSWORD: secret
    volumes:
      - ./db_init/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s
      timeout: 5s
      retries: 50

  keycloak-provisioning:
    image: ghcr.io/noumenadigital/npl-breakfast-demo/keycloak-provisioning:latest
    build:
      context: keycloak-provisioning
    command: /local.sh
    volumes:
      - keycloak-provisioning:/state
    env_file:
      - .env
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-welcome}
      KEYCLOAK_URL: http://keycloak:11000
      TF_VAR_default_password: ${SEED_TEST_USERS_PASSWORD:-welcome}
      TF_VAR_systemuser_secret: super-secret-system-security-safe
      TF_VAR_app_name: ${VITE_NC_APP_SLUG:-breakfast}
    depends_on:
      keycloak:
        condition: service_healthy

  keycloak:
    image: ghcr.io/noumenadigital/npl-breakfast-demo/keycloak:latest
    build:
      context: keycloak
    command: |
      start
      --spi-events-listener-jboss-logging-success-level=info
      --spi-events-listener-jboss-logging-error-level=error
      --health-enabled=true
      --http-enabled=true
      --http-port=11000
      --hostname-strict=false
      --hostname=http://localhost:11000
      --hostname-admin=http://localhost:11000
      --hostname-backchannel-dynamic=true
      --metrics-enabled=true
      --db=postgres
    ports:
      - "11000:11000"
      - "9000:9000"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-welcome}
      KC_DB_URL: jdbc:postgresql://keycloak-db/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: testing
      KC_HEALTH_ENABLED: "true"
    depends_on:
      keycloak-db:
        condition: service_started
    healthcheck:
      test: curl http://localhost:9000/health || exit 1
      interval: 1s
      retries: 60

  keycloak-db:
    image: postgres:14.4-alpine
    mem_limit: 256m
    ports:
      - "11040:5432"
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: testing
      ENV: DOCKER
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s
      timeout: 5s
      retries: 50

  inspector:
    image: ghcr.io/noumenadigital/packages/inspector:latest
    env_file:
      - .env
    environment:
      - NPL_ENGINE_URL=http://engine:12001
      - KEYCLOAK_URL=${VITE_KEYCLOAK_URL:-http://keycloak:11000}
      - KEYCLOAK_REALM=${VITE_NC_APP_SLUG:-breakfast}
      - KEYCLOAK_CLIENT_ID=${VITE_NC_APP_SLUG:-breakfast}
    depends_on:
      nginx-proxy:
        condition: service_started
    ports:
      - "8070:8080"

  npl-mcp-server:
    image: ghcr.io/noumenadigital/npl-mcp-server:latest
    ports:
      - "8000:8000"
    environment:
      - OPENAPI_URL=http://engine:12000/npl/objects/-/openapi.json
      - API_BASE_URL=http://engine:12000/
      - KEYCLOAK_URL=http://keycloak:11000/ # maybe has to be changed to localhost for the mcp client to work in vscode.dev?
      - KEYCLOAK_REALM=breakfast
      - KEYCLOAK_CLIENT_ID=npl-mcp
      - KEYCLOAK_CLIENT_SECRET=... # todo: copy secret from keycloak
      - ALLOWED_REDIRECT_URIS=http://localhost:*,http://127.0.0.1:*
    depends_on:
      engine:
        condition: service_healthy
      keycloak:
        condition: service_healthy